Repository knative-extensions/security-guard, pull requests merged in 2022-08, with the labels that each got.

#2 Init
  OWNERS
  README.md
  test/presubmit-tests.sh
  test/presubmit-tests.sh.tmpl
Labels: size/M, approved, lgtm

#4 Update OWNERS
  OWNERS
Labels: size/XS, approved, lgtm

#6 README.md
  README.md
  pkg/pluginterfaces/README.md
  pkg/qpoption/README.md
  pkg/test-gate/README.md
Labels: size/L, approved, lgtm

#7 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, approved, lgtm, skip-review

#3 Add qp option and test gate
  pkg/pluginterfaces/pluginterfaces.go
  pkg/pluginterfaces/pluginterfaces_test.go
  pkg/qpoption/qpoption.go
  pkg/qpoption/qpoption_test.go
  pkg/test-gate/test-gate.go
  pkg/test-gate/test-gate_test.go
Labels: approved, lgtm, size/XXL

#10 Create update-deps.sh
  hack/update-deps.sh
Labels: approved, size/S, lgtm

#11 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#12 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#13 get repo in order
  README.md
  img/guard.png
Labels: approved, size/S, lgtm

#14 chmod update-deps.sh +x
  hack/update-deps.sh
Labels: size/XS, approved, lgtm

#9 V1 and Count
  pkg/apis/wsecurity/v1alpha1/README.md
  pkg/apis/wsecurity/v1alpha1/TODO.md
  pkg/apis/wsecurity/v1alpha1/count.go
  pkg/apis/wsecurity/v1alpha1/count_test.go
  pkg/apis/wsecurity/v1alpha1/v1alpha1.go
  pkg/apis/wsecurity/v1alpha1/v1alpha1_test.go
Labels: approved, size/XL, lgtm

#17 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#21 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#18 align naming to documentation QPOptions
  go.mod
  go.sum
  pkg/apis/wsecurity/v1alpha1/TODO.md
  pkg/qpoption/qpoption.go
  pkg/qpoption/qpoption_test.go
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/http/handler/timeout.go
  vendor/knative.dev/serving/pkg/queue/constants.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#22 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/M, skip-review

#23 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#24 Fix README badges
  README.md
Labels: size/XS, approved, lgtm
