Repository knative-extensions/security-guard, pull requests merged in 2022-11, with the labels that each got.

#89 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#91 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#83 lables
  cmd/guard-service/main.go
  cmd/guard-service/services_test.go
  pkg/guard-gate/client_test.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/token-handler.go
  pkg/guard-kubemgr/token-handler_test.go
Labels: size/M, approved, lgtm

#90 Removed limitations for consumed objects
  pkg/apis/guard/v1alpha1/README.md
  pkg/apis/guard/v1alpha1/asciiFlags.go
  pkg/apis/guard/v1alpha1/body.go
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/flagSlice.go
  pkg/apis/guard/v1alpha1/ipSet.go
  pkg/apis/guard/v1alpha1/keyval.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
Labels: size/L, approved, lgtm

#94 Update linting/style for go1.19
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/pluginterfaces/pluginterfaces.go
Labels: approved, size/S, lgtm

#92 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#95 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/serving/pkg/autoscaler/metrics/sample_size.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#87 Add TLS between gate and service
  cmd/guard-rproxy/main.go
  cmd/guard-service/main.go
  config/deploy/guard-service.yaml
  config/deploy/secured-helloworld.yaml
  config/deploy/secured-layered-myapp.yaml
  config/resources/gateAccount.yaml
  config/resources/serviceAccount.yaml
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/gate_test.go
  pkg/guard-gate/state.go
  pkg/guard-gate/state_test.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/token-handler_test.go
  pkg/qpoption/qpoption.go
Labels: size/L, approved, lgtm

#97 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#98 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#105 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: approved, size/S, lgtm
