Repository knative-extensions/security-guard, pull requests merged in 2022-09, with the labels that each got.

#25 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#20 SimpleVal - with private interface methods and public type-specific method
  pkg/apis/wsecurity/v1alpha1/asciiFlags.go
  pkg/apis/wsecurity/v1alpha1/asciiFlags_test.go
  pkg/apis/wsecurity/v1alpha1/count.go
  pkg/apis/wsecurity/v1alpha1/flagSlice.go
  pkg/apis/wsecurity/v1alpha1/flagSlice_test.go
  pkg/apis/wsecurity/v1alpha1/simpleVal.go
  pkg/apis/wsecurity/v1alpha1/simpleVal_test.go
  pkg/apis/wsecurity/v1alpha1/v1alpha1.go
  pkg/apis/wsecurity/v1alpha1/v1alpha1_test.go
Labels: approved, size/XL, lgtm

#28 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/serving/pkg/http/handler/timeout.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#29 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#26 keyval, QS, Headers, URL, MediaType
  pkg/apis/wsecurity/v1alpha1/httpHeaders.go
  pkg/apis/wsecurity/v1alpha1/httpHeaders_test.go
  pkg/apis/wsecurity/v1alpha1/httpMediaType.go
  pkg/apis/wsecurity/v1alpha1/httpMediaType_test.go
  pkg/apis/wsecurity/v1alpha1/keyval.go
  pkg/apis/wsecurity/v1alpha1/keyval_test.go
  pkg/apis/wsecurity/v1alpha1/queryString.go
  pkg/apis/wsecurity/v1alpha1/queryString_test.go
  pkg/apis/wsecurity/v1alpha1/url.go
  pkg/apis/wsecurity/v1alpha1/url_test.go
Labels: approved, size/XL, lgtm

#27 Body which is based on Structured
  pkg/apis/wsecurity/v1alpha1/body.go
  pkg/apis/wsecurity/v1alpha1/body_test.go
  pkg/apis/wsecurity/v1alpha1/ipSet.go
  pkg/apis/wsecurity/v1alpha1/structuredProfiler.go
  pkg/apis/wsecurity/v1alpha1/structuredProfiler_test.go
Labels: approved, size/XL, lgtm

#34 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#33 6th v1alpha1 session
  pkg/apis/wsecurity/v1alpha1/httpReq.go
  pkg/apis/wsecurity/v1alpha1/httpReq_test.go
  pkg/apis/wsecurity/v1alpha1/httpResp.go
  pkg/apis/wsecurity/v1alpha1/httpResp_test.go
  pkg/apis/wsecurity/v1alpha1/pod.go
  pkg/apis/wsecurity/v1alpha1/pod_test.go
  pkg/apis/wsecurity/v1alpha1/sessionData.go
  pkg/apis/wsecurity/v1alpha1/sessionData_test.go
Labels: approved, lgtm, size/XXL

#37 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/http/handler/timeout.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#40 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/autoscaler/metrics/collector.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#41 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm

#42 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm

#44 Kube mgr
  deploy/gateAccount.yaml
  deploy/guardiansCrd.yaml
  deploy/serviceAccount.yaml
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/guard-kubemgr_test.go
Labels: approved, lgtm, size/XXL

#47 Fix links
  README.md
  cmd/guard-service/README.md
  pkg/guard-gate/README.md
Labels: size/XS, approved, lgtm

#48 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/imdario/mergo/LICENSE
  third_party/VENDOR-LICENSE/github.com/spf13/pflag/LICENSE
  third_party/VENDOR-LICENSE/sigs.k8s.io/structured-merge-diff/v4/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/github.com/imdario/mergo/.gitignore
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/generators/rules/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/hack/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/pkg/metrics/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/pkg/tracing/config/OWNERS
  vendor/knative.dev/pkg/websocket/OWNERS
  vendor/knative.dev/serving/pkg/activator/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/knative.dev/serving/pkg/http/OWNERS
  vendor/knative.dev/serving/pkg/logging/OWNERS
  vendor/knative.dev/serving/pkg/metrics/OWNERS
  vendor/knative.dev/serving/pkg/queue/OWNERS
  vendor/knative.dev/serving/pkg/resources/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/json/OWNERS
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, size/XL, lgtm

#49 Utils
  pkg/apis/guard/v1alpha1/TODO.md
  pkg/apis/guard/v1alpha1/sessionData.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/guard-kubemgr_test.go
  pkg/guard-utils/log.go
  pkg/guard-utils/stats.go
  pkg/guard-utils/stats_test.go
  pkg/guard-utils/ticker.go
  pkg/guard-utils/ticker_test.go
Labels: size/L, approved, lgtm

#51 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#53 reduce coverage for now
  .codecov.yaml
Labels: size/XS, approved, lgtm

#50 watch + services
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  cmd/guard-service/services_test.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/watcher.go
  pkg/guard-kubemgr/watcher_test.go
Labels: approved, lgtm, size/XXL

#55 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/knative.dev/security-guard/LICENSE
  vendor/modules.txt
Labels: approved, size/S, lgtm

#56 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/S, lgtm

#52 gateClient+gateState
  pkg/guard-gate/README.md
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/img/gateSwArch.png
  pkg/guard-gate/state.go
  pkg/guard-gate/state_test.go
Labels: approved, size/XL, lgtm

#58 updates
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/guard-kubemgr/watcher.go
  pkg/guard-kubemgr/watcher_test.go
  pkg/guard-utils/log.go
  pkg/guard-utils/log_test.go
  pkg/guard-utils/ticker.go
  pkg/guard-utils/ticker_test.go
Labels: size/L, approved, lgtm

#54 guard-sevice
  cmd/guard-service/README.md
  cmd/guard-service/auth.go
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  cmd/guard-service/services_test.go
  pkg/guard-utils/santize.go
  pkg/guard-utils/santize_test.go
  playground/examples/guardians/cm.yaml
  playground/examples/guardians/crd.yaml
Labels: approved, lgtm, size/XXL

#59 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#60 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
