Repository knative-extensions/security-guard, pull requests merged in 2022-10, with the labels that each got.

#61 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#63 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#65 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#62 release
  hack/generate-yamls.sh
  hack/release.sh
Labels: size/L, approved, lgtm

#67 Config features
  config/deploy/config-features.yaml
Labels: approved, size/S, lgtm

#72 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#74 doc udpate
  README.md
  pkg/apis/guard/v1alpha1/TODO.md
Labels: size/M, approved, lgtm

#75 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/S, lgtm

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#80 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#77 Authenticate guard-service requests
  cmd/guard-rproxy/main.go
  cmd/guard-rproxy/main_test.go
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  cmd/guard-service/services_test.go
  config/resources/gateAccount.yaml
  config/resources/serviceAccount.yaml
  go.mod
  go.sum
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/state.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/token-handler.go
  pkg/guard-kubemgr/token-handler_test.go
  pkg/guard-utils/log.go
  pkg/guard-utils/log_test.go
  vendor/github.com/golang-jwt/jwt/v4/LICENSE
  vendor/github.com/golang-jwt/jwt/v4/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/doc.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/hmac.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/none.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/rsa.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/signing_method.go
  vendor/github.com/golang-jwt/jwt/v4/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#82 fixReadme
  cmd/guard-rproxy/README.md
Labels: approved, size/S, lgtm

#85 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/golang-jwt/jwt/v4/LICENSE
  vendor/github.com/golang-jwt/jwt/v4/.gitignore
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#86 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#88 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/constants.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: size/M, approved, lgtm
