Repository knative-extensions/security-guard, pull requests merged in 2022-12, with the labels that each got.

#106 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/control-protocol/pkg/certificates/certs.go
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#107 Changing Decide() to build a DecisionTree as a response
  config/resources/serviceAccount.yaml
  pkg/apis/guard/v1alpha1/asciiFlags.go
  pkg/apis/guard/v1alpha1/asciiFlags_test.go
  pkg/apis/guard/v1alpha1/body.go
  pkg/apis/guard/v1alpha1/body_test.go
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/count_test.go
  pkg/apis/guard/v1alpha1/envelop.go
  pkg/apis/guard/v1alpha1/envelop_test.go
  pkg/apis/guard/v1alpha1/flagSlice.go
  pkg/apis/guard/v1alpha1/flagSlice_test.go
  pkg/apis/guard/v1alpha1/httpHeaders.go
  pkg/apis/guard/v1alpha1/httpHeaders_test.go
  pkg/apis/guard/v1alpha1/httpMediaType.go
  pkg/apis/guard/v1alpha1/httpMediaType_test.go
  pkg/apis/guard/v1alpha1/httpReq.go
  pkg/apis/guard/v1alpha1/httpReq_test.go
  pkg/apis/guard/v1alpha1/httpResp.go
  pkg/apis/guard/v1alpha1/httpResp_test.go
  pkg/apis/guard/v1alpha1/ipSet.go
  pkg/apis/guard/v1alpha1/ipSet_test.go
  pkg/apis/guard/v1alpha1/keyval.go
  pkg/apis/guard/v1alpha1/keyval_test.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/pod_test.go
  pkg/apis/guard/v1alpha1/queryString.go
  pkg/apis/guard/v1alpha1/queryString_test.go
  pkg/apis/guard/v1alpha1/sessionData.go
  pkg/apis/guard/v1alpha1/sessionData_test.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/set_test.go
  pkg/apis/guard/v1alpha1/simpleVal.go
  pkg/apis/guard/v1alpha1/simpleVal_test.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
  pkg/apis/guard/v1alpha1/structuredProfiler_test.go
  pkg/apis/guard/v1alpha1/url.go
  pkg/apis/guard/v1alpha1/url_test.go
  pkg/apis/guard/v1alpha1/v1alpha1.go
  pkg/apis/guard/v1alpha1/v1alpha1_test.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/session.go
  pkg/guard-gate/session_test.go
  pkg/guard-gate/state.go
  pkg/guard-kubemgr/guard-kubemgr.go
Labels: approved, lgtm, size/XXL

#109 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#110 E2E tests
  .github/workflows/e2e.yaml
  config/resources/serviceAccount.yaml
  test/e2e/deploy/httptestCrd.yaml
  test/e2e/e2e-tests.sh
  test/e2e/services/httptest/httptest.go
Labels: approved, size/XL, lgtm

#111 Release updates towards operator
  config/deploy/config-features.yaml
  config/deploy/queue-proxy.yaml
  hack/generate-yamls.sh
Labels: approved, size/S, lgtm

#115 release-0.2: update-codegen.sh + gofmt
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/pluginterfaces/pluginterfaces.go
Labels: size/M, approved, lgtm

#118 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/modules.txt
Labels: size/M, approved, lgtm
