Repository knative-extensions/security-guard, pull requests merged in 2023-06, with the labels that each got.

#211 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#215 Get certificate reconciler from networking instead of control-protocol
  cmd/create-knative-secrets/main.go
  cmd/guard-rproxy/main.go
  go.mod
  go.sum
  pkg/guard-gate/client.go
  pkg/qpoption/qpoption.go
  third_party/VENDOR-LICENSE/knative.dev/control-protocol/pkg/certificates/LICENSE
  vendor/knative.dev/control-protocol/LICENSE
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/knative.dev/networking/pkg/certificates/certs.go
  vendor/knative.dev/networking/pkg/certificates/constants.go
  vendor/knative.dev/networking/pkg/certificates/key_pair.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#216 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#214 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#218 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/generators/rules/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/hack/OWNERS
  vendor/knative.dev/serving/pkg/activator/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/knative.dev/serving/pkg/http/OWNERS
  vendor/knative.dev/serving/pkg/logging/OWNERS
  vendor/knative.dev/serving/pkg/metrics/OWNERS
  vendor/knative.dev/serving/pkg/queue/OWNERS
  vendor/knative.dev/serving/pkg/resources/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/json/OWNERS
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, size/XL, lgtm

#220 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
