Repository knative-extensions/security-guard, pull requests merged in 2023-10, with the labels that each got.

#251 Update e2e.yaml
  .github/workflows/e2e.yaml
Labels: size/XS, approved, lgtm

#250 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, skip-review

#252 fix pod pile update
  KUBERNETES.md
  hack/kind/deployKind.sh
  hack/kind/deployKnativeKind.sh
  pkg/guard-gate/gate.go
Labels: size/M, approved, lgtm

#253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#255 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, approved, lgtm

#256 :bug: add length-check for tokens
  cmd/guard-service/main.go
Labels: kind/bug, size/XS, approved, needs-ok-to-test, lgtm

#257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/serving/pkg/queue/readiness/probe.go
  vendor/modules.txt
Labels: size/L, approved, lgtm
