Repository knative-extensions/security-guard, pull requests merged in 2023-09, with the labels that each got.

#238 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/queue/certificate/watcher.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#237 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, skip-review

#239 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#240 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#236 Security fixes: Limit number of keys learned, Limit key sizes learned, fixes in accordance to security review
  SECURITY.md
  cmd/guard-rproxy/main.go
  cmd/guard-service/main.go
  cmd/guard-webhook/main.go
  cmd/random-request-sender/main.go
  go.mod
  go.sum
  hack/kind/deployKnativeKindFromLatest.sh
  pkg/apis/guard/v1alpha1/asciiFlags.go
  pkg/apis/guard/v1alpha1/flagSlice.go
  pkg/apis/guard/v1alpha1/keyval.go
  pkg/apis/guard/v1alpha1/limit.go
  pkg/apis/guard/v1alpha1/simpleVal.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/session.go
  pkg/guard-gate/session_test.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/iodup/iodup.go
  vendor/github.com/klauspost/cpuid/v2/.gitignore
  vendor/github.com/klauspost/cpuid/v2/.goreleaser.yml
  vendor/github.com/klauspost/cpuid/v2/CONTRIBUTING.txt
  vendor/github.com/klauspost/cpuid/v2/LICENSE
  vendor/github.com/klauspost/cpuid/v2/README.md
  vendor/github.com/klauspost/cpuid/v2/cpuid.go
  vendor/github.com/klauspost/cpuid/v2/cpuid_386.s
  vendor/github.com/klauspost/cpuid/v2/cpuid_amd64.s
  vendor/github.com/klauspost/cpuid/v2/cpuid_arm64.s
  vendor/github.com/klauspost/cpuid/v2/detect_arm64.go
  vendor/github.com/klauspost/cpuid/v2/detect_ref.go
  vendor/github.com/klauspost/cpuid/v2/detect_x86.go
  vendor/github.com/klauspost/cpuid/v2/featureid_string.go
  vendor/github.com/klauspost/cpuid/v2/os_darwin_arm64.go
  vendor/github.com/klauspost/cpuid/v2/os_linux_arm64.go
  vendor/github.com/klauspost/cpuid/v2/os_other_arm64.go
  vendor/github.com/klauspost/cpuid/v2/os_safe_linux_arm64.go
  vendor/github.com/klauspost/cpuid/v2/os_unsafe_linux_arm64.go
  vendor/github.com/klauspost/cpuid/v2/test-architectures.sh
  vendor/github.com/zeebo/xxh3/.gitignore
  vendor/github.com/zeebo/xxh3/LICENSE
  vendor/github.com/zeebo/xxh3/Makefile
  vendor/github.com/zeebo/xxh3/README.md
  vendor/github.com/zeebo/xxh3/_compat.c
  vendor/github.com/zeebo/xxh3/accum_generic.go
  vendor/github.com/zeebo/xxh3/accum_stubs_amd64.go
  vendor/github.com/zeebo/xxh3/accum_stubs_other.go
  vendor/github.com/zeebo/xxh3/accum_vector_avx512_amd64.s
  vendor/github.com/zeebo/xxh3/accum_vector_avx_amd64.s
  vendor/github.com/zeebo/xxh3/accum_vector_sse_amd64.s
  vendor/github.com/zeebo/xxh3/consts.go
  vendor/github.com/zeebo/xxh3/hash128.go
  vendor/github.com/zeebo/xxh3/hash128_seed.go
  vendor/github.com/zeebo/xxh3/hash64.go
  vendor/github.com/zeebo/xxh3/hash64_seed.go
  vendor/github.com/zeebo/xxh3/hasher.go
  vendor/github.com/zeebo/xxh3/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#242 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#245 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#244 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/klauspost/cpuid/v2/LICENSE
  third_party/VENDOR-LICENSE/github.com/zeebo/xxh3/LICENSE
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#247 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/queue/health/probe.go
  vendor/knative.dev/serving/pkg/queue/readiness/probe.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#248 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
