Repository knative-extensions/security-guard, pull requests merged in 2023-01, with the labels that each got.

#117 Add Prepare() to API Objects
  pkg/apis/guard/v1alpha1/asciiFlags.go
  pkg/apis/guard/v1alpha1/body.go
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/envelop.go
  pkg/apis/guard/v1alpha1/flagSlice.go
  pkg/apis/guard/v1alpha1/httpHeaders.go
  pkg/apis/guard/v1alpha1/httpMediaType.go
  pkg/apis/guard/v1alpha1/httpReq.go
  pkg/apis/guard/v1alpha1/httpResp.go
  pkg/apis/guard/v1alpha1/ipSet.go
  pkg/apis/guard/v1alpha1/keyval.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/queryString.go
  pkg/apis/guard/v1alpha1/sessionData.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/simpleVal.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
  pkg/apis/guard/v1alpha1/url.go
  pkg/apis/guard/v1alpha1/v1alpha1.go
  pkg/guard-gate/state.go
Labels: size/L, approved, lgtm

#116 Concurrency fix
  cmd/guard-service/services.go
  pkg/guard-gate/client.go
  pkg/guard-gate/state.go
  pkg/guard-utils/stats.go
Labels: size/L, approved, lgtm

#119 Add Limit
  pkg/apis/guard/v1alpha1/envelop.go
  pkg/apis/guard/v1alpha1/limit.go
  pkg/apis/guard/v1alpha1/limit_test.go
  pkg/apis/guard/v1alpha1/sessionData_test.go
  pkg/apis/guard/v1alpha1/simpleVal.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/state.go
  test/e2e/deploy/httptestCrd.yaml
  test/e2e/e2e-tests.sh
Labels: approved, size/XL, lgtm

#120 Merge Fuse with Learn
  cmd/guard-service/services.go
  pkg/apis/guard/v1alpha1/asciiFlags.go
  pkg/apis/guard/v1alpha1/body.go
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/envelop.go
  pkg/apis/guard/v1alpha1/flagSlice.go
  pkg/apis/guard/v1alpha1/guardianSpec.go
  pkg/apis/guard/v1alpha1/httpHeaders.go
  pkg/apis/guard/v1alpha1/httpMediaType.go
  pkg/apis/guard/v1alpha1/httpReq.go
  pkg/apis/guard/v1alpha1/httpResp.go
  pkg/apis/guard/v1alpha1/ipSet.go
  pkg/apis/guard/v1alpha1/keyval.go
  pkg/apis/guard/v1alpha1/limit.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/pod_test.go
  pkg/apis/guard/v1alpha1/queryString.go
  pkg/apis/guard/v1alpha1/sessionData.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/simpleVal.go
  pkg/apis/guard/v1alpha1/structuredProfiler.go
  pkg/apis/guard/v1alpha1/url.go
  pkg/apis/guard/v1alpha1/v1alpha1.go
  pkg/apis/guard/v1alpha1/v1alpha1_test.go
  pkg/guard-gate/client.go
  pkg/guard-utils/stats.go
Labels: size/L, approved, lgtm

#122 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#123 fixTls
  pkg/guard-gate/gate.go
Labels: size/XS, approved, lgtm

#125 Tls script
  config/deploy/queue-proxy.yaml
  hack/installUsingOperatorWithTLS.sh
  hack/installUsingOperatorWithoutTLS.sh
  hack/setTLS.sh
  hack/unsetTLS.sh
Labels: size/L, approved, lgtm

#128 Improved Scripts and Logs
  cmd/guard-service/main.go
  config/deploy/guard-service.yaml
  hack/installUsingOperatorWithTLS.sh
  hack/installUsingOperatorWithoutTLS.sh
  hack/setTLS.sh
  hack/unsetTLS.sh
  pkg/guard-gate/client.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/state.go
  pkg/guard-kubemgr/watcher.go
Labels: size/L, approved, lgtm

#130 Print if tls is on
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/gate_test.go
  pkg/guard-gate/state.go
Labels: size/M, approved, lgtm

#129 repeat tests with TLS
  .github/workflows/e2e.yaml
  test/e2e/deploy/httptest1Crd.yaml
  test/e2e/deploy/httptest2Crd.yaml
  test/e2e/e2e-tests.sh
Labels: size/L, approved, lgtm

#132 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#137 fix pod alerts (take 2)
  .github/workflows/e2e.yaml
  pkg/apis/guard/v1alpha1/pod.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/session.go
  pkg/guard-gate/state.go
Labels: size/M, approved, lgtm

#135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#142 Improve e2e tests - also help debug e2e tests
  .github/workflows/e2e.yaml
  test/e2e/deploy/httptest1Crd.yaml
  test/e2e/deploy/httptest2Crd.yaml
  test/e2e/e2e-tests.sh
Labels: size/M, approved, lgtm

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/S, lgtm
