Repository knative-extensions/security-guard, pull requests merged in 2023-02, with the labels that each got.

#145 Support Analysis of Req/Resp Body
  pkg/apis/guard/v1alpha1/body.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/session.go
  pkg/guard-gate/state.go
  pkg/iodup/iodup.go
  pkg/iodup/iodup_test.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
Labels: approved, size/XL, lgtm

#150 [main] Upgrade to latest dependencies
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
Labels: approved, size/S, lgtm

#151 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#153 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#152 Alert aggregation
  cmd/guard-rproxy/main.go
  cmd/guard-rproxy/main_test.go
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  cmd/guard-service/services_test.go
  pkg/apis/guard/v1alpha1/v1alpha1.go
  pkg/apis/guard/v1alpha1/v1alpha1_test.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/client.go
  pkg/guard-gate/client_test.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/gate_test.go
  pkg/guard-gate/session.go
  pkg/guard-gate/session_test.go
  pkg/guard-gate/state.go
  pkg/guard-gate/state_test.go
  pkg/guard-kubemgr/guard-kubemgr.go
  pkg/guard-kubemgr/token-handler.go
  pkg/guard-kubemgr/token-handler_test.go
  test/e2e/e2e-tests.sh
Labels: approved, lgtm, size/XXL

#154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#160 log request Alert when in Block mode
  pkg/guard-gate/gate.go
Labels: approved, size/S, lgtm

#159 Added Prepare() in guardService, fixed wrong array treatment in Learn()
  CODING.md
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/set_test.go
Labels: size/M, approved, lgtm

#166 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/L, approved, lgtm

#168 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#170 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#169 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review

#171 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#177 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#181 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/language/language.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#176 Improve guard service learning
  README.md
  cmd/guard-rproxy/main.go
  cmd/guard-service/main.go
  cmd/guard-service/main_test.go
  cmd/guard-service/services.go
  cmd/guard-service/services_test.go
  cmd/queue/main.go
  pkg/apis/guard/v1alpha1/count.go
  pkg/apis/guard/v1alpha1/pod.go
  pkg/apis/guard/v1alpha1/set.go
  pkg/apis/guard/v1alpha1/zz_generated.deepcopy.go
  pkg/guard-gate/client.go
  pkg/guard-gate/gate.go
  pkg/guard-gate/gate_test.go
  pkg/guard-gate/session.go
  pkg/guard-gate/session_test.go
  pkg/guard-gate/state.go
  pkg/guard-gate/state_test.go
  pkg/pluginterfaces/pluginterfaces.go
  pkg/pluginterfaces/pluginterfaces_test.go
  pkg/qpoption/qpoption.go
Labels: approved, size/XL, lgtm
