Repository knative-extensions/security-guard, pull requests merged in 2023-11, with the labels that each got.

#259 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, size/S, lgtm

#262 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, approved, lgtm

#264 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#266 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#265 Upgrade to `go 1.21` and add `toolchain go1.21.4`
  .github/workflows/e2e.yaml
  go.mod
Labels: size/XS, approved, lgtm
