Repository knative-extensions/security-guard, pull requests merged in 2023-03, with the labels that each got.

#186 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#185 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#187 Align env, fix some bugs
  .github/workflows/e2e.yaml
  KUBERNETES.md
  cmd/guard-rproxy/README.md
  cmd/guard-rproxy/main.go
  cmd/guard-rproxy/main_test.go
  cmd/guard-service/main.go
  cmd/guard-service/services.go
  cmd/queue/auth.go
  config-kubernetes/deploy/secured-helloworld.yaml
  config-kubernetes/deploy/secured-layered-myapp.yaml
  hack/kind/deployKind.sh
  hack/kind/deployKindFromLatest.sh
  hack/kind/deployKnativeKindFromLatest.sh
  pkg/guard-gate/gate.go
  pkg/guard-gate/gate_test.go
  pkg/guard-gate/state.go
  test/e2e/deploy/httptest1Crd.yaml
  test/e2e/services/httptest/httptest.go
Labels: size/L, approved, lgtm

#188 releaseUpdates
  hack/generate-yamls.sh
  hack/kind/deployKind.sh
  hack/kind/deployKnativeKind.sh
  test/e2e/services/httptest/deploy.yaml
  test/e2e/services/httptest/guardian.yaml
Labels: size/L, approved, lgtm

#189 fix token bug and buildKind.sh
  hack/kind/deployKind.sh
  pkg/guard-gate/client.go
Labels: size/M, approved, lgtm

#191 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review
