Repository knative-extensions/security-guard, pull requests merged in 2024-03, with the labels that each got.

#277 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review

#282 E2E tests fixes
  .codecov.yaml
  .github/workflows/e2e.yaml
  config/deploy/create-secrets.yaml
  hack/kind/deployKnativeKindFromLatest.sh
  hack/kind/kind-config.yaml
Labels: size/M, approved, lgtm

#279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/queue/readiness/probe.go
  vendor/knative.dev/serving/pkg/queue/readiness/probe_encoding.go
  vendor/knative.dev/serving/pkg/queue/sharedmain/main.go
  vendor/modules.txt
Labels: size/L, approved, lgtm

#281 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, skip-review

#285 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#286 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#287 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#288 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
