Repository knative-extensions/security-guard, pull requests merged in 2024-08, with the labels that each got.

#308 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#307 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/modules.txt
Labels: size/M, approved, lgtm

#310 Stop currently broken code generation
  hack/update-codegen.sh
Labels: size/XS, approved, lgtm
