Repository knative-extensions/security-guard, pull requests merged in 2024-12, with the labels that each got.

#330 Updated kind version
  .github/workflows/e2e.yaml
Labels: size/XS, approved, lgtm

#328 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#329 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, skip-review
